ExamApp/Models/ErrorViewModel.cs
using System;

namespace ExamApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamApp/Controllers/ExamController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Services.Services;
using System.Linq;
using Models.Parameters.Exam;
using Services.Services.ExamService;
using Models.Dtos;
using System.Collections.Generic;
using Services.Services.StudentService;
using Services.Services.SubjectService;
using Models.Parameters.Subject;
using Models.Parameters.Student;

namespace ExamApp.Controllers
{
    public class ExamController : Controller
    {
        private readonly IExamService _examService;
        private readonly IStudentService _studentService;
        private readonly ISubjectService _subjectService;

        public ExamController(IExamService examService, IStudentService studentService, ISubjectService subjectService)
        {
            _examService = examService;
            _studentService = studentService;
            _subjectService = subjectService;
        }

        public async Task<IActionResult> Index()
        {
            await FillSubjects();
            await FillStudents();
            return await GetExams();
        }


        [HttpPost]
        public async Task<IActionResult> Index(AddExamInput input)
        {
            if (ModelState.IsValid)
            {
                ContainerResult<bool> result = await _examService.AddExam(input);

                if (!result.IsSuccess)
                {
                    TempData["Errors"] = result.ErrorList.Select(x => x.ErrorMessage).ToList();
                }
                else
                {
                    TempData["Success"] = "Exam succesfully added";
                }

                return RedirectToAction();
            }
            else
            {
                await FillSubjects();
                await FillStudents();
                await GetExams();
                return View(input);
            }
        }


        private async Task<IActionResult> GetExams()
        {
            ContainerResult<GetExamsOutput> result = await _examService.GetExams();

            if (!result.IsSuccess)
            {
                return View();
            }

            ViewBag.Exams = result.Output.Exams;

            return View();
        }

        private async Task<IActionResult> FillSubjects()
        {
            ContainerResult<GetSubjectsOutput> result = await _subjectService.GetSubjects();

            if (!result.IsSuccess)
            {
                return View();
            }

            List<SubjectDto> subjects = result.Output.Subjects;

            ViewBag.Subjects = subjects;

            return View();
        }

        private async Task<IActionResult> FillStudents()
        {
            ContainerResult<GetStudentsOutput> result = await _studentService.GetStudents();

            if (!result.IsSuccess)
            {
                return View();
            }

            List<StudentDto> students = result.Output.Students;
            ViewBag.Students = students;
            return View();
        }
    }
}

ExamApp/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Models.Parameters.Student;
using Services.Services.StudentService;
using System.Threading.Tasks;
using Services.Services;
using System.Linq;

namespace ExamApp.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;

        public StudentController(IStudentService studentService)
        {
            _studentService = studentService;
        }

        public async Task<IActionResult> Index()
        {
            return await GetStudents();
        }


        [HttpPost]
        public async Task<IActionResult> Index(AddStudentInput input)
        {
            if (ModelState.IsValid)
            {
                ContainerResult<bool> result = await _studentService.AddStudent(input);

                if (!result.IsSuccess)
                {
                    TempData["Errors"] = result.ErrorList.Select(x => x.ErrorMessage).ToList();
                }
                else
                {
                    TempData["Success"] = "Student succesfully added";
                }

                return RedirectToAction();
            }
            else
            {
                await GetStudents();
                return View(input);
            }
        }


        private async Task<IActionResult> GetStudents()
        {
            ContainerResult<GetStudentsOutput> result = await _studentService.GetStudents();

            if (!result.IsSuccess)
            {
                return View();
            }

            ViewBag.Students = result.Output.Students;

            return View();
        }
    }
}

ExamApp/Controllers/SubjectController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Services.Services;
using System.Linq;
using Services.Services.SubjectService;
using Models.Parameters.Subject;

namespace ExamApp.Controllers
{
    public class SubjectController : Controller
    {
        private readonly ISubjectService _subjectService;

        public SubjectController(ISubjectService subjectService)
        {
            _subjectService = subjectService;
        }

        public async Task<IActionResult> Index()
        {
            return await GetSubjects();
        }


        [HttpPost]
        public async Task<IActionResult> Index(AddSubjecInput input)
        {
            if (ModelState.IsValid)
            {
                ContainerResult<bool> result = await _subjectService.AddSubject(input);

                if (!result.IsSuccess)
                {
                    TempData["Errors"] = result.ErrorList.Select(x => x.ErrorMessage).ToList();
                }
                else
                {
                    TempData["Success"] = "Subject succesfully added";
                }

                return RedirectToAction();
            }
            else
            {
                await GetSubjects();
                return View(input);
            }
        }


        private async Task<IActionResult> GetSubjects()
        {
            ContainerResult<GetSubjectsOutput> result = await _subjectService.GetSubjects();

            if (!result.IsSuccess)
            {
                return View();
            }

            ViewBag.Subjects = result.Output.Subjects;

            return View();
        }
    }
}

ExamApp/Views/Exam/Index.cshtml
@using Models.Parameters.Exam
@model AddExamInput

<div class="text-center">
    <h4>Exams</h4>
    <hr />
    <div class="row justify-content-between">
        <div class="col-md-3">
            <form asp-action="Index">
                <div class="form-group">
                    <label asp-for="SubjectCode" class="control-label"></label>
                    <select asp-for="SubjectCode" class="form-control">
                        @if (ViewBag.Subjects != null)
                        {
                            @foreach (var subject in ViewBag.Subjects)
                            {
                        <option value="@subject.Code">@subject.Name (@subject.ClassNumber)</option>
                            }
                        }
                    </select>
                    <span asp-validation-for="SubjectCode" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StudentId" class="control-label"></label>
                    <select asp-for="StudentId" class="form-control">
                        @if (ViewBag.Students != null)
                        {
                            @foreach (var student in ViewBag.Students)
                            {
                        <option value="@student.Id">@student.Name (@student.ClassNumber)</option>
                            }
                        }
                    </select>
                    <span asp-validation-for="StudentId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Score" class="control-label"></label>
                    <input asp-for="Score" class="form-control" />
                    <span asp-validation-for="Score" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BeginDate" class="control-label"></label>
                    <input asp-for="BeginDate" class="form-control" />
                    <span asp-validation-for="BeginDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Add Exam" class="btn btn-primary" />
                </div>
            </form>

            <div class="row">
                @if (TempData["Errors"] != null)
                {
                    @foreach (var error in (IEnumerable<string>)TempData["Errors"])
                    {
                        <h4 class="text-danger custom-warning" style="margin-left:4%">@error</h4>
                    }
                }

                @if (TempData["Success"] != null)
                {
                    <h4 class="text-success custom-warning" style="margin-left:4%">@TempData["Success"]</h4>
                }
            </div>
        </div>

        <div class="col-md-1"></div>

        <div class="col-md-8">
            <table class="table data-table">
                <thead>
                    <tr>
                        <th scope="col">Student's id</th>
                        <th scope="col">Student's name</th>
                        <th scope="col">Student's surname</th>
                        <th scope="col">Subject's code</th>
                        <th scope="col">Subject's name</th>
                        <th scope="col">Teacher's name</th>
                        <th scope="col">Teacher's surname</th>
                        <th scope="col">Class number</th>
                        <th scope="col">Score</th>
                        <th scope="col">Begin date</th>
                    </tr>
                </thead>
                <tbody>
                    @if (ViewBag.Exams != null)
                    {
                        @foreach (var exam in ViewBag.Exams)
                        {
                            <tr>
                                <th scope="row">@exam.StudentId</th>
                                <td>@exam.StudentName</td>
                                <td>@exam.StudentSurname</td>
                                <td>@exam.SubjectCode</td>
                                <td>@exam.SubjectName</td>
                                <td>@exam.TeacherName</td>
                                <td>@exam.TeacherSurname</td>
                                <td>@exam.ClassNumber</td>
                                <td>@exam.Score</td>
                                <td>@exam.BeginDate.ToString("MM/dd/yyyy HH:mm")</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

ExamApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Exam application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="shortcart icon" href="~/logo.png">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Subject" asp-action="Index">Exam application</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index">Subjects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exam" asp-action="Index">Exams</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Samir Hasanov
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ExamApp/Views/Student/Index.cshtml
@using Models.Parameters.Student
@model AddStudentInput

<div class="text-center">
    <h4>Students</h4>
    <hr />
    <div class="row justify-content-between">
        <div class="col-md-3">
            <form asp-action="Index">
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Surname" class="control-label"></label>
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ClassNumber" class="control-label"></label>
                    <input asp-for="ClassNumber" class="form-control" />
                    <span asp-validation-for="ClassNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Register Student" class="btn btn-primary" />
                </div>
            </form>

            <div class="row">
                @if (TempData["Errors"] != null)
                {
                    @foreach (var error in (IEnumerable<string>)TempData["Errors"])
                    {
                        <h4 class="text-danger custom-warning" style="margin-left:4%">@error</h4>
                    }
                }

                @if (TempData["Success"] != null)
                {
                    <h4 class="text-success custom-warning" style="margin-left:4%">@TempData["Success"]</h4>
                }
            </div>
        </div>

        <div class="col-md-1"></div>

        <div class="col-md-8">
            <table class="table data-table">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Name</th>
                        <th scope="col">Surname</th>
                        <th scope="col">Class number</th>
                    </tr>
                </thead>
                <tbody>
                    @if (ViewBag.Students != null)
                    {
                        @foreach (var student in ViewBag.Students)
                        {
                            <tr>
                                <th scope="row">@student.Id</th>
                                <td>@student.Name</td>
                                <td>@student.Surname</td>
                                <td>@student.ClassNumber</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

ExamApp/Views/Subject/Index.cshtml
@using Models.Parameters.Subject
@model AddSubjecInput

<div class="text-center">
    <h4>Subjects</h4>
    <hr />
    <div class="row justify-content-between">
        <div class="col-md-3">
            <form asp-action="Index">
                <div class="form-group">
                    <label asp-for="Code" class="control-label"></label>
                    <input asp-for="Code" class="form-control" />
                    <span asp-validation-for="Code" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ClassNumber" class="control-label"></label>
                    <input asp-for="ClassNumber" class="form-control" />
                    <span asp-validation-for="ClassNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TeacherName" class="control-label"></label>
                    <input asp-for="TeacherName" class="form-control" />
                    <span asp-validation-for="TeacherName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="TeacherSurname" class="control-label"></label>
                    <input asp-for="TeacherSurname" class="form-control" />
                    <span asp-validation-for="TeacherSurname" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Register Subject" class="btn btn-primary" />
                </div>
            </form>

            <div class="row">
                @if (TempData["Errors"] != null)
                {
                    @foreach (var error in (IEnumerable<string>)TempData["Errors"])
                    {
                        <h4 class="text-danger custom-warning" style="margin-left:4%">@error</h4>
                    }
                }

                @if (TempData["Success"] != null)
                {
                    <h4 class="text-success custom-warning" style="margin-left:4%">@TempData["Success"]</h4>
                }
            </div>
        </div>

        <div class="col-md-1"></div>

        <div class="col-md-8">
            <table class="table data-table">
                <thead>
                    <tr>
                        <th scope="col">Code</th>
                        <th scope="col">Name</th>
                        <th scope="col">ClassNumber</th>
                        <th scope="col">TeacherName</th>
                        <th scope="col">TeacherSurname</th>
                    </tr>
                </thead>
                <tbody>
                    @if (ViewBag.Subjects != null)
                    {
                        @foreach (var subject in ViewBag.Subjects)
                        {
                            <tr>
                                <th scope="row">@subject.Code</th>
                                <td>@subject.Name</td>
                                <td>@subject.ClassNumber</td>
                                <td>@subject.TeacherName</td>
                                <td>@subject.TeacherSurname</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>